// ==UserScript==
// @name        JOKE BLOCKER
// @namespace   Violentmonkey Scripts
// @updateURL    https://raw.githubusercontent.com/moongazer07/moongazer07.github.io/main/JOKE%20BLOCKER.js
// @downloadURL  https://raw.githubusercontent.com/moongazer07/moongazer07.github.io/main/JOKE%20BLOCKER.js
// @version     1.0
// @description block pranks with joke blocker
// @author      moongazer07
// @icon         https://cdn.discordapp.com/attachments/887488897934848041/908176275225604116/oie_SwLbuM3DM3GQ.jpg
// @run-at        document-start
// @run-at        document-load
// @include       youareanidiot.cc
// @include       hurr-durr.cc
// @include       https://www.youtube.com/watch?v=oHg5SJYRHA0
// @include       https://www.youtube.com/watch?v=8ybW48rKBME
// @include       https://www.youtube.com/watch?v=ub82Xb1C8os
// @include       https://www.youtube.com/watch?v=qDs7KkGcQ6M
// @include       https://www.google.com/search?q=rick+roll&oq=rick+roll&aqs=chrome.0.69i59j69i57j69i60l4j69i61l2.1381j0j1&sourceid=chrome&ie=UTF-8
// @include       https://www.google.com/search?q=rick+roll&sxsrf=AOaemvJz3XXRPxsYPIjhhSpRQ6aTV4N0pw:1636557614874&gbv=2&sei=LuOLYfzXNPKD_QbT4asY
// @include       https://www.google.com/search?q=rick+roll&oq=rick+roll
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ
// @include       https://www.youtube.com/watch?v=TslQz-J2JmA&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=2&t=0s
// @include       https://www.youtube.com/watch?v=TslQz-J2JmA
// @include       https://www.youtube.com/watch?v=_muM7QSWTjY&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=3&t=0s
// @include       https://www.youtube.com/watch?v=_muM7QSWTjY
// @include       https://www.youtube.com/watch?v=zP-olb-Qq4o&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=4&t=0s
// @include       https://www.youtube.com/watch?v=zP-olb-Qq4o
// @include       https://www.youtube.com/watch?v=CqnrLFgTO7U&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=5&t=0s
// @include       https://www.youtube.com/watch?v=CqnrLFgTO7U
// @include       https://www.youtube.com/watch?v=UMeJuq0gnjM&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=6&t=0s
// @include       https://www.youtube.com/watch?v=UMeJuq0gnjM
// @include       https://www.youtube.com/watch?v=CFqbF-gcK4Q&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=7&t=0s
// @include       https://www.youtube.com/watch?v=CFqbF-gcK4Q
// @include       https://www.youtube.com/watch?v=gI1syKBptrU&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=8&t=0s
// @include       https://www.youtube.com/watch?v=gI1syKBptrU
// @include       https://www.youtube.com/watch?v=snDSOJjKwZo&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=9&t=0s
// @include       https://www.youtube.com/watch?v=snDSOJjKwZo
// @include       https://www.youtube.com/watch?v=6qG8svVlAj8&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=10&t=0s
// @include       https://www.youtube.com/watch?v=6qG8svVlAj8
// @include       https://www.youtube.com/watch?v=zgNuHWFCDqw&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=11&t=0s
// @include       https://www.youtube.com/watch?v=zgNuHWFCDqw
// @include       https://www.youtube.com/watch?v=LN4uZbjeTQE&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=12&t=0s
// @include       https://www.youtube.com/watch?v=LN4uZbjeTQE
// @include       https://www.youtube.com/watch?v=FyNzDR6BD90&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=13&t=0s
// @include       https://www.youtube.com/watch?v=FyNzDR6BD90
// @include       https://www.youtube.com/watch?v=HH3I8ouaLMA&list=PLCV6ATR_bbCaNdCScp2D5-9aI2i56TwoO&index=14&t=0s
// @include       https://www.youtube.com/watch?v=HH3I8ouaLMA
// @include       https://www.youtube.com/watch?v=xfr64zoBTAQ
// @include       https://www.youtube.com/watch?v=bCh5IlXTckA&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=2&t=0s
// @include       https://www.youtube.com/watch?v=bCh5IlXTckA
// @include       https://www.youtube.com/watch?v=GjyUk_Ebb4o&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=3&t=0s
// @include       https://www.youtube.com/watch?v=GjyUk_Ebb4o
// @include       https://www.youtube.com/watch?v=INbRpclIFsE&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=4&t=0s
// @include       https://www.youtube.com/watch?v=INbRpclIFsE
// @include       https://www.youtube.com/watch?v=X7Y0F_OGFKw&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=5&t=0s
// @include       https://www.youtube.com/watch?v=X7Y0F_OGFKw
// @include       https://www.youtube.com/watch?v=oJl25bABYac&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=6&t=0s
// @include       https://www.youtube.com/watch?v=oJl25bABYac
// @include       https://www.youtube.com/watch?v=E458nb_pPmk&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=7&t=0s
// @include       https://www.youtube.com/watch?v=E458nb_pPmk
// @include       https://www.youtube.com/watch?v=LjQZaD9EEJ0&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=8&t=0s
// @include       https://www.youtube.com/watch?v=LjQZaD9EEJ0
// @include       https://www.youtube.com/watch?v=9oxRDJjAQKI&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=9&t=0s
// @include       https://www.youtube.com/watch?v=9oxRDJjAQKI
// @include       https://www.youtube.com/watch?v=iiUIi5b9RlE&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=10&t=0s
// @include       https://www.youtube.com/watch?v=iiUIi5b9RlE
// @include       https://www.youtube.com/watch?v=SsiHLiXBlcM&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=11&t=0s
// @include       https://www.youtube.com/watch?v=SsiHLiXBlcM
// @include       https://www.youtube.com/watch?v=NL_Iceg5TmY&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=12&t=0s
// @include       https://www.youtube.com/watch?v=NL_Iceg5TmY
// @include       https://www.youtube.com/watch?v=JkcHqN6YswU&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=13&t=0s
// @include       https://www.youtube.com/watch?v=JkcHqN6YswU
// @include       https://www.youtube.com/watch?v=s0akG-V_Y30&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=14&t=0s
// @include       https://www.youtube.com/watch?v=s0akG-V_Y30
// @include       https://www.youtube.com/watch?v=ikFZLI4HLpQ&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=15&t=0s
// @include       https://www.youtube.com/watch?v=ikFZLI4HLpQ
// @include       https://www.youtube.com/watch?v=Kiz3PM387FI&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=16&t=0s
// @include       https://www.youtube.com/watch?v=Kiz3PM387FI
// @include       https://www.youtube.com/watch?v=qxeokP0n6V0&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=17&t=0s
// @include       https://www.youtube.com/watch?v=qxeokP0n6V0
// @include       https://www.youtube.com/watch?v=s99hC5WUwjo&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=18&t=0s
// @include       https://www.youtube.com/watch?v=s99hC5WUwjo
// @include       https://www.youtube.com/watch?v=06pBzAlItwI&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=20&t=0s
// @include       https://www.youtube.com/watch?v=06pBzAlItwI
// @include       https://www.youtube.com/watch?v=lHyeAtiiL18&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=21&t=0s
// @include       https://www.youtube.com/watch?v=lHyeAtiiL18
// @include       https://www.youtube.com/watch?v=Q53-mWHvxJo&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=22
// @include       https://www.youtube.com/watch?v=Q53-mWHvxJo
// @include       https://www.youtube.com/watch?v=d4N5LnsNpF0&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=24&t=0s
// @include       https://www.youtube.com/watch?v=d4N5LnsNpF0
// @include       https://www.youtube.com/watch?v=d4N5LnsNpF0&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=24&t=21s
// @include       https://www.youtube.com/watch?v=vkbQmH5MPME&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=25&t=0s
// @include       https://www.youtube.com/watch?v=vkbQmH5MPME
// @include       https://www.youtube.com/watch?v=kczWpSN6emg&list=PLVbxVQf7e2KRz1J34jFf7jDJFDT9lvnQ9&index=26&t=0s
// @include       https://www.youtube.com/watch?v=kczWpSN6emg
// @include       https://www.youtube.com/watch?v=GHMjD0Lp5DY
// @include       https://www.youtube.com/watch?v=DLzxrzFCyOs
// @include       https://www.youtube.com/watch?v=YddwkMJG1Jo
// @include       https://www.youtube.com/watch?v=iik25wqIuFo
// @include       https://www.youtube.com/watch?v=QB7ACr7pUuE
// @include       https://www.youtube.com/watch?v=OWWu05YYbNI
// @include       https://www.youtube.com/watch?v=qXCitbKV754
// @include       https://www.youtube.com/watch?v=dRV6NaciZVk
// @include       https://www.youtube.com/watch?v=dPmZqsQNzGA
// @include       https://www.youtube.com/watch?v=6-HUgzYPm9g
// @include       https://www.youtube.com/watch?v=r8tXjJL3xcM
// @include       https://www.youtube.com/watch?v=d1YBv2mWll0
// @include       https://www.youtube.com/watch?v=mTYNJZEaruI
// @include       https://www.youtube.com/watch?v=uUc_8PUXXp4
// @include       https://www.youtube.com/watch?v=iEaGkJ8RKFw
// @include       https://www.youtube.com/watch?v=mbfg7JP_mms
// @include       https://www.youtube.com/watch?v=gssO-O1TIUE
// @include       https://www.youtube.com/watch?v=I-6GB_m9seI
// @include       https://www.youtube.com/watch?v=fpaELVzFwDw
// @include       https://www.youtube.com/watch?v=eUwTFXNfRpU
// @include       https://www.youtube.com/watch?v=1uEBJChO6fc
// @include       https://www.youtube.com/watch?v=mTYNJZEaruI&t=1s
// @include       https://www.youtube.com/watch?v=i-DqL1UJdAE
// @include       https://www.youtube.com/watch?v=VZp4NYkpUNY
// @include       https://www.youtube.com/watch?v=uxIsiTo4VJo
// @include       https://www.youtube.com/watch?v=_0719DxMOUY
// @include       https://www.youtube.com/watch?v=xm_EMOdpDhc
// @include       https://www.youtube.com/watch?v=atiNprQmjks
// @include       https://www.youtube.com/watch?v=FGEUClII8x0
// @include       https://www.youtube.com/watch?v=dS9DO6kx-Ek
// @include       https://www.youtube.com/watch?v=uYMIMPVK1vU
// @include       https://www.youtube.com/watch?v=rfp7FbsnsbU
// @include       https://www.youtube.com/watch?v=mrThFRR3n8A
// @include       https://www.youtube.com/watch?v=_3wkyerSBpw
// @include       https://www.youtube.com/watch?v=LWErcuHm_C4
// @include       https://www.youtube.com/watch?v=j8PxqgliIno
// @include       https://www.youtube.com/watch?v=AACOcpA8i-U
// @include       https://www.youtube.com/watch?v=DqzjKO-0WNE
// @include       https://www.youtube.com/watch?v=bIwVIx5pp88
// @include       https://www.youtube.com/watch?v=HnfkEVtetuE
// @include       https://www.youtube.com/watch?v=MCjlo7PtXMQ
// @include       https://www.youtube.com/watch?v=a6pbjksYUHY
// @include       https://www.youtube.com/watch?v=hUWtgoVH6bc
// @include       https://www.youtube.com/watch?v=fM2oZo6wFE0
// @include       https://www.youtube.com/watch?v=2vaZaALaGTY
// @include       https://www.youtube.com/watch?v=ll-mQPDCn-U
// @include       https://www.youtube.com/watch?v=RvBwypGUkPo
// @include       https://www.youtube.com/watch?v=-pHhb4biR9k
// @include       https://www.youtube.com/watch?v=sSSOG8g7PFg
// @include       http://completleyfakerickrolllink.com/
// @include       https://www.youtube.com/watch?v=AyOqGRjVtls
// @include       https://www.youtube.com/watch?v=Tt7bzxurJ1I
// @include       https://app.studiesweekly.com/online/crossword/6568
// @include       https://www.youtube.com/watch?v=ub82Xb1C8os&feature=youtu.be
// @include       https://www.youtube.com/watch?v=_YGlEL8lD8U
// @include       https://chat.google.com/u/1/room/AAAAlh6XD3E
// @include       https://www.youtube.com/watch?v=d0tGBCCE0lc
// @include       https://www.youtube.com/watch?v=84Gxj9FUldQ
// @include       https://www.secretrickroll.com/
// @include       https://www.thisworldthesedays.com/ok318.html
// @include       https://chrome.google.com/webstore/detail/rickroller/cfbiaglcehihlnllafbiiciihhlegdbl
// @include       https://accounts.google.com/signin/chrome/sync/identifier?ssp=1&continue=https%3A%2F%2Fwww.google.com%2F&flowName=GlifDesktopChromeSync
// @include       https://www.youtube.com/watch?v=tzYPr9w22VU&feature=youtu.be
// @include       https://www.youtube.com/watch?v=HLE9dZ6kUfY
// @include       https://www.youtube.com/watch?v=c_j0lFHxgNk
// @include       https://www.youtube.com/watch?v=V-_O7nl0Ii0
// @include       https://www.youtube.com/watch?v=oHg5SJYRHA0&feature=youtu.be&ab_channel=cotter548
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO
// @include       https://www.youtube.com/watch?v=FqdmWQ-ACv0&feature=youtu.be
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=FLGy5mvghUIELHASnWhAxVhg&index=6&t=0s
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&app=desktop
// @include       https://www.youtube.com/watch?v=ahnfLZKwnTg
// @include       https://www.youtube.com/watch?v=2942BB1JXFk
// @include       https://www.youtube.com/watch?v=2mt9TRVq-Lo
// @include       https://www.youtube.com/watch?v=PtypaFzR680
// @include       https://www.youtube.com/watch?v=Lrj2Hq7xqQ8
// @include       https://www.youtube.com/watch?v=VbUuB1aN2DA
// @include       https://www.youtube.com/watch?v=xvFZjo5PgG0
// @include       https://www.youtube.com/watch?v=th0pH9srXRY
// @include       https://www.latlmes.com/breaking/your-sensational-news-headline-here-1
// @include       https://www.youtube.com/watch?v=tkNhPYXHrmU
// @include       https://www.facebook.com/groups/2678666319074792/permalink/2874367409504681/
// @include       https://www.instagram.com/direct/t/340282366841710300949128220550085402179
// @include       https://www.youtube.com/post/UgwVlt0J2E7eu8Z5lbp4AaABCQ
// @include       https://www.youtube.com/watch?v=m1yWUWhamj4
// @include       https://www.latlmes.com/entertainment/coraline-live-action-remake-planned-1
// @include       https://www.youtube.com/watch?v=6_b7RDuLwcI
// @include       https://www.youtube.com/watch?v=G8iEMVr7GFg
// @include       https://www.youtube.com/watch?v=6mhmcwmgWbA
// @include       https://www.youtube.com/watch?v=SpZ2FsEfwP4
// @include       https://www.youtube.com/watch?v=H01BwSD9eyQ
// @include       https://www.youtube.com/watch?v=nrsnN23tmUA
// @include       https://www.youtube.com/watch?v=8mkofgRW1II
// @include       https://www.youtube.com/watch?v=rAx5LIul1N8
// @include       https://www.youtube.com/watch?v=sO4wVSA9UPs
// @include       https://www.youtube.com/watch?v=rrs0B_LM898
// @include       https://www.youtube.com/watch?v=doEqUhFiQS4
// @include       https://www.youtube.com/watch?v=epyRUp0BhrA
// @include       https://www.youtube.com/watch?v=uK5WDo_3s7s
// @include       https://www.youtube.com/watch?v=wzSVOcgKq04
// @include       https://www.youtube.com/watch?v=7B--1KArxow
// @include       https://www.youtube.com/watch?v=rbsPu1z3ugQ
// @include       https://www.youtube.com/watch?v=ptw2FLKXDQE
// @include       https://www.youtube.com/watch?v=E50L-JYWm3w
// @include       https://www.youtube.com/watch?v=8leAAwMIigI
// @include       https://www.youtube.com/watch?v=ByqFY-Boq5Y
// @include       https://www.youtube.com/watch?v=E4ihJMQUmUQ
// @include       https://www.youtube.com/watch?v=cjBHXvBYw5s
// @include       https://www.youtube.com/watch?v=xaazUgEKuVA
// @include       https://www.youtube.com/watch?v=TzXXHVhGXTQ
// @include       https://www.youtube.com/watch?v=Uj1ykZWtPYI
// @include       https://www.youtube.com/watch?v=EE-xtCF3T94
// @include       https://www.youtube.com/watch?v=0SoNH07Slj0
// @include       https://www.youtube.com/watch?v=j5a0jTc9S10
// @include       https://www.youtube.com/watch?v=nHRbZW097Uk
// @include       https://www.youtube.com/watch?v=BjDebmqFRuc
// @include       https://www.youtube.com/watch?v=Gc2u6AFImn8
// @include       https://www.youtube.com/watch?v=8VFzHYtOARw
// @include       https://www.youtube.com/watch?v=cSAp9sBzPbc
// @include       https://www.youtube.com/watch?v=Dx5i1t0mN78
// @include       https://www.youtube.com/watch?v=Oo0twK2ZbLU
// @include       https://www.youtube.com/watch?v=cvh0nX08nRw
// @include       https://www.youtube.com/watch?v=lXMskKTw3Bc
// @include       https://www.youtube.com/watch?v=7z_1E8VGJOw
// @include       https://www.youtube.com/watch?v=VgojnNgmgVs
// @include       https://www.youtube.com/watch?v=5wOXc03RwVA
// @include       https://www.youtube.com/watch?v=j5a0jTc9S10&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=11
// @include       https://www.youtube.com/watch?v=gPkZS92WCIo
// @include       https://bjupressonline.com/bju/c_video_player.php?c=2774&video=146103
// @include       https://www.youtube.com/watch?v=34Ig3X59_qA
// @include       https://mail.watertowncsd.org/owa/#path=/mail
// @include       https://www.tomorrowtides.com/anti-rickroll.html
// @include       https://www.youtube.com/watch?v=6mhmcwmgWbA&list=LLh0zI6HBoJh3w94SSuZs4Hg&index=161
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&feature=youtu.be
// @include       https://www.latlmes.com/breaking/twitch-improves-growth-on-its-platform-1
// @include       https://www.imdb.com/user/ur128317655/watchlist?ref_=nv_usr_wl_all_0
// @include       https://www.youtube.com/watch?v=HPk-VhRjNI8&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=2
// @include       https://www.youtube.com/watch?v=HPk-VhRjNI8&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=1
// @include       https://www.youtube.com/watch?v=fC7oUOUEEi4
// @include       https://www.youtube.com/watch?v=HPk-VhRjNI8
// @include       https://www.google.co.uk/?safe=active&ssui=on
// @include       https://www.youtube.com/watch?v=QGwamuKU1us
// @include       https://www.youtube.com/watch?v=eBGIQ7ZuuiU
// @include       https://www.youtube.com/watch?v=0BMZpcLgiSs
// @include       https://www.youtube.com/watch?v=Yb6dZ1IFlKc
// @include       https://www.youtube.com/watch?v=Uj1ykZWtPYI&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=2
// @include       https://www.youtube.com/watch?v=WG5eFa4Nsl4
// @include       https://www.youtube.com/watch?v=jG674XALnVY
// @include       https://www.youtube.com/watch?v=O91DT1pR1ew
// @include       https://www.youtube.com/watch?v=o2HsFJkDn5Q
// @include       https://www.youtube.com/watch?v=HE4EnL6-2as
// @include       https://www.youtube.com/watch?v=q2G9AWeanqY
// @include       https://www.youtube.com/watch?v=Wjy3o0FoLYc
// @include       https://www.youtube.com/watch?v=hAq443fhyDo
// @include       https://www.youtube.com/watch?v=uPETMD7ACeQ
// @include       https://www.sanfransentinel.com/mcdonalds-cup-size-scam.html
// @include       https://discord.com/channels/@me/841833097484828702
// @include       https://therickroll.com/
// @include       https://bingobaker.com/#b1dd8d2e5ffc21aa
// @include       https://www.youtube.com/watch?v=ycRjXHhscPw
// @include       https://www.youtube.com/watch?v=iSIcWKEVQIw&t=0s
// @include       https://discord.com/channels/@me/834423155418071040
// @include       https://www.youtube.com/watch?v=fcZXfoB2f70
// @include       https://www.youtube.com/watch?v=bIXm-Q-Xa4s
// @include       https://www.youtube.com/watch?v=XqZsoesa55w
// @include       https://www.thisworldthesedays.com/
// @include       https://www.youtube.com/watch?v=bwndZ6vyMC4
// @include       https://www.youtube.com/watch?v=wtOW1CxHvNY
// @include       https://www.theraleighregister.com/
// @include       https://www.youtube.com/watch?v=4aYgaO6DP3s
// @include       https://www.youtube.com/watch?v=IO9XlQrEt2Y
// @include       https://www.youtube.com/watch?v=kqHqhEbN_SY
// @include       https://www.youtube.com/watch?v=j5a0jTc9S10&t=0s
// @include       https://www.youtube.com/watch?v=gvGyS5j9aFY
// @include       https://www.youtube.com/watch?v=ykLGXWb-AtA
// @include       https://www.youtube.com/watch?v=7r5ez4Lt6x8
// @include       https://www.youtube.com/watch?v=jYsuNj2Eclg
// @include       https://www.youtube.com/watch?v=dxKyvydL1Ew
// @include       https://www.youtube.com/watch?v=072tU1tamd0
// @include       https://www.youtube.com/watch?v=JIWcDz-PyLU
// @include       https://www.youtube.com/watch?v=UWugyiIXfiM
// @include       https://www.youtube.com/watch?v=9NcPvmk4vfo
// @include       https://www.pixiv.net/en/artworks/76913250
// @include       https://play.numo.nl/exercises/232778/exercise
// @include       https://www.youtube.com/watch?v=x31tDT-4fQw
// @include       https://www.youtube.com/watch?v=HIcSWuKMwOw
// @include       https://www.youtube.com/watch?v=S5o9g22BdXw
// @include       https://www.youtube.com/watch?v=UFNsLikZk3I
// @include       https://www.bing.com/videos/search?q=rickroll+dif+link&docid=608003550594228143&mid=4E3C3C2EDC4FA71659FA4E3C3C2EDC4FA71659FA&view=detail&FORM=VIRE
// @include       https://www.bing.com/videos/search?q=rickroll+dif+link&view=detail&mid=3556557A69D6ED6904703556557A69D6ED690470&FORM=VIRE
// @include       https://www.youtube.com/watch?v=5q0gJs2eYB4
// @include       https://www.thisworldthesedays.com/wwwdrugsandmanymorearticlescomjashmeetisgay1.html
// @include       https://scratch.mit.edu/discuss/youtube/yPYZpwSpKmA/
// @include       https://www.youtube.com/watch?v=yPYZpwSpKmA
// @include       https://www.youtube.com/watch?v=xvFZjo5PgG0&ab_channel=DeeckPeeck
// @include       https://www.youtube.com/watch?v=iik25wqIuFo&ab_channel=Rickroll%2Cbutwithadifferentlink
// @include       https://www.youtube.com/watch?v=YddwkMJG1Jo&ab_channel=Rickroll%2Cbutwithadifferentlink
// @include       https://www.youtube.com/watch?v=E9de-cmycx8
// @include       https://www.youtube.com/watch?v=-51AfyMqnpI
// @include       https://www.youtube.com/watch?v=mCdA4bJAGGk
// @include       https://www.youtube.com/watch?v=2ocykBzWDiM
// @include       https://www.youtube.com/watch?v=sQnoZUR6fvY
// @include       https://video.link/w/RA92c
// @include       https://www.schooltube.com/media/Rick+Astley+-+Never+Gonna+Give+You+Up/1_ld4nfqve
// @include       https://www.youtube.com/watch?v=_rBQP7UQ7Kg
// @include       https://www.youtube.com/watch?v=FpFztrJbksg
// @include       https://www.youtube.com/watch?app=desktop&v=j5a0jTc9S10
// @include       https://www.youtube.com/watch?v=L9MEdkgWLEY
// @include       https://scratch.mit.edu/discuss/youtube/dQw4w9WgXcQ/
// @include       https://www.youtube.com/watch?v=v1POP-m76ac
// @include       https://www.youtube.com/watch?app=desktop&v=dQw4w9WgXcQ
// @include       https://www.youtube.com/watch?v=ZHesfCUU2Fw
// @include       https://www.youtube.com/watch?v=f-tLr7vONmc&t=10s
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=0s
// @include       https://www.youtube.com/watch?v=LsqFoKwIJqw
// @include       https://www.youtube.com/watch?v=Tt7bzxurJ1I&list=PLLRhw_zIKh78JY6W-oBBk3LAQBYy7uhGY
// @include       https://www.youtube.com/watch?v=50qKHsRCr9Y
// @include       https://a.captchadecode.com/robot4/index.html?c=b7ee3924-1734-4c3d-9bf8-2576a807d8ed&a=l99875#
// @include       https://a.captchadecode.com/robot37/index.html?c=8d1ae7f0-ec31-4edd-a1d7-e63cd2e316c0&a=l99875#
// @include       https://lp.perfectpremiumapp.com/downloadDD0/?mrddp=2&mrddz=2579905&mrdd=610184e8f92ca00001dee3ba&mrddr=444285814235468758&extid=coapebbcbmmbgeddbbbnlgbliohjgcjn
// @include       https://lp.perfectpremiumapp.com/downloadDD0/?mrddp=2&mrddz=2579905&mrdd=610184f3f92ca00001df0c73&mrddr=444285863371739336&extid=coapebbcbmmbgeddbbbnlgbliohjgcjn
// @include       https://adcleanerpage.com/?scenario=promo5s&trackingdomain=mignished-sility.com&source_id=e6773e24-cd6f-4dcb-a1f9-72b3990ec835&cep=Am3g76TwQUVeaggDOPtV-Ii-rzo31ouHldFVpHBeAq9w4FdybYtjQ8z6vuswlaD1AxdcbD051yIUS1CqKMbk3VMgElt4kGK0Us6XUv06XWgJlx5shOOd3RAb31_mbSPZ8SGqS9B1je2WSGuDXjAwoeKXDkVk9zdRKzorhRQHFVLxV2okyq08X53UJnYi9J_TsNbMBWTb1ec3Jx3ltdSKrRxCiXuXgM1pffOE3qiPHJ-RDiYF415XaNnqLTfYBkODo-4KklwyideYyw9a3PuGGpvbMjnqJgC3s3VICnyzHe2ddgt1snJAqvozLtWbz4JqzBXb1i4hXqDlRMsu1lepHo7qpNkZAaTH22_R7dQZM2avkBH2y98A89Iu64pNPwKKG5yIhXb5VL9tbLrGKulN8o9maUBn-wmArqy2GDYULLrwYekiFW929g98RBgWVMVB0HhDKU-m0oDUdZul86YvVdANNpqxKpGmdvBLv61kkrIQMOSPiZF3FGDi-iA8rgdmIYv08grC0u9JpJJfw__TLii90FZw9Hrk7vUGo0Eg6bseggZisewj9umnuVBWS0zL0mkceXM9DBBZGSWc9Q3fGgarMy-fcedksuPfVDLpgqQIcGgaS_4rv6yJqkAD4C7_S0KxCPAaC8uLK6bpmEuk0W2sVkt43fifb9k6PujKp97uVgdLg7vpoLUNh0KgdTTIv5qkKuCLVmMNG1gCHr5zqSwyQQuDt6CLVwyn59Nc2m0&lptoken=16b2279e497213b9323f&zoneid=2579905&bannerid=9810533&browser=chrome&os=windows&device=desktop®ion=mo&isp=charter+communications&useragent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F92.0.4515.107+Safari%2F537.36&language=en&connectiontype=cable&cost=0.041653&visitor_id=444285900705248050
// @include       https://lp.perfectpremiumapp.com/downloadDD0/?mrddp=2&mrddz=2579905&mrdd=6101850af92ca00001df5829&mrddr=444285961820451102&extid=coapebbcbmmbgeddbbbnlgbliohjgcjn
// @include       https://www.user-shield-check.com/information-may-be-exposed/?sxid=7vtdh0l1f8w4&var9=aHR0cHM6Ly9hZC5wcm9wZWxsZXJhZHMuY29tL2NvbnZlcnNpb24ucGhwP2FpZD0xMDQwODk0JnBpZD0mdGlkPTgxMjk2JnZpc2l0b3JfaWQ9e2V4dGVybmFsaWR9&externalid=444286011799773716&var1=45754732579905&var2=9839309&ttorigin=7vtdh0l1f8w4
// @include       https://lp.perfectpremiumapp.com/downloadDD0/?mrddp=2&mrddz=2579905&mrdd=61018521f92ca00001df9e90&mrddr=444286054640394752&extid=coapebbcbmmbgeddbbbnlgbliohjgcjn
// @include       https://aggie.io/
// @include       https://www.youtube.com/watch?v=3KPY-gjmHWA
// @include       https://www.youtube.com/watch?v=EE-xtCF3T94&t=10s
// @include       https://discord.com/channels/@me/819001459474563090
// @include       https://www.emghypnosis.com/index.php
// @include       https://a.captchadecode.com/robot4/index.html?c=ec33af1e-28d5-431c-8907-9f4292ae7fb1&a=l99875#
// @include       https://c.captchadecode.com/robot4/index.html?c=ec33af1e-28d5-431c-8907-9f4292ae7fb1#
// @include       https://www.youtube.com/watch?v=Svj1bZz2mXw
// @include       https://www.youtube.com/watch?v=WpOD6nivkV8&list=RDWpOD6nivkV8&start_radio=1
// @include       https://www.youtube.com/watch?v=sELlGrdQ3KI
// @include       https://www.youtube.com/watch?v=kYJNyD2jOCk
// @include       https://www.youtube.com/watch?v=ftqaCFiKkX8
// @include       https://www.youtube.com/watch?v=uNeXW5nwDVs
// @include       https://web.whatsapp.com/
// @include       https://stephaneginier.com/sculptgl/
// @include       https://www.youtube.com/watch?v=4G0uhL6W2_k
// @include       https://www.youtube.com/watch?v=D-IvHf_1nbA
// @include       https://discord.com/channels/@me/824018444663783484
// @include       https://mangelrex.newgrounds.com/trophies
// @include       https://www.youtube.com/watch?v=HPk-VhRjNI8&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx
// @include       https://www.youtube.com/watch?v=xuCO7-DLCaA
// @include       https://www.youtube.com/watch?v=YZ21U1P-iwU
// @include       https://www.youtube.com/watch?v=EE-xtCF3T94&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=4
// @include       https://www.youtube.com/watch?v=V-_O7nl0Ii0&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=5
// @include       https://www.youtube.com/watch?v=vkbQmH5MPME&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=6
// @include       https://www.youtube.com/watch?v=8O_ifyIIrN4&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=7
// @include       https://www.youtube.com/watch?v=ikFZLI4HLpQ&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=8
// @include       https://www.youtube.com/watch?v=iSIcWKEVQIw
// @include       https://www.youtube.com/watch?v=sXwaRjU7Tj0
// @include       https://www.thisworldthesedays.com/you3107.html
// @include       https://www.youtube.com/watch?v=hRbkAezmW78
// @include       https://discord.com/channels/807128596677918730/838740674408611850
// @include       https://obmontessorifairview.orangeapps.ph/oa_school/home
// @include       https://live132.entrarlive.co/html5client/join?sessionToken=ctcfgs9veqz0snmq
// @include       https://www.youtube.com/watch?v=N82AE95jM7I
// @include       https://www.youtube.com/watch?v=f-tLr7vONmc
// @include       https://www.youtube.com/watch?v=vbmmpy2cB6w&ab_channel=Heqt
// @include       https://www.youtube.com/watch?v=clwgJ_T2cdQ
// @include       https://student.lingoace.com/?_gl=1*1os5404*_ga*NDg1Nzg0Mzg5LjE2MjMzNzI5NTQ.*_ga_254C2Q7KNL*MTYyMzQzMzcwMC4yLjAuMTYyMzQzMzcwMC4w#/home
// @include       https://www.youtube.com/watch?v=YJWSAJjkTsI
// @include       https://www.youtube.com/watch?v=QtBDL8EiNZo
// @include       https://www.youtube.com/watch?v=R93Uy0dQazE
// @include       https://www.youtube.com/
// @include       https://vivaldi.com/features/#pk_campaign=sd&pk_kwd=features-en-au
// @include       https://www.youtube.com/watch?v=VYBDS_vap0c&t=0s
// @include       https://www.youtube.com/watch?v=QMW4AqbuSGg
// @include       https://www.youtube.com/watch?v=Ln09LU2sfhs
// @include       https://www.youtube.com/watch?v=K7XHy8nppf4
// @include       https://www.youtube.com/watch?v=BCa6gS3uybU
// @include       https://www.youtube.com/watch?v=ZXpThNX9IRc
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=19s
// @include       https://www.youtube.com/watch?v=-X0ubuxLEHE
// @include       https://www.thisworldthesedays.com/opening-skrzynek-i-budowanie-chmurki-ip-wwoojjc.html
// @include       https://www.youtube.com/watch?v=bBYoRpCs-J8&ab_channel=AlsoNotJ
// @include       https://makerrzcss.plexicz.com/priceing
// @include       https://www.thisworldthesedays.com/free-warzone-skins.html
// @include       https://www.messenger.com/t/3960951430676685
// @include       https://www.minuddannelse.net/Node/forloeb/01da8f2d-b745-4884-9f34-bd7fdc39401a?aarsplanguid=39fe18b6-abfa-b65e-4cf6-f072823bdc28#8916740d-0451-4eb2-974d-34a4299a722d
// @include       https://www.youtube.com/watch?v=jkn5y86EFuU
// @include       https://www.minuddannelse.net/Node/forloeb/01da8f2d-b745-4884-9f34-bd7fdc39401a?aarsplanguid=39fe18b6-abfa-b65e-4cf6-f072823bdc28#4375ed38-d18f-4912-ad75-179efb3bee9f
// @include       https://rickrolled.com/
// @include       https://en.wikipedia.org/wiki/Rickrolling
// @include       https://knowyourmeme.com/memes/rickroll
// @include       https://inviterick.com/
// @include       https://www.washingtonpost.com/technology/2021/08/10/rick-astley-rickroll-youtube/
// @include       https://www.theverge.com/tldr/22289657/never-gonna-give-you-up-4k
// @include       https://www.dafk.net/what/
// @include       https://shattereddisk.github.io/rickroll/rickroll.mp4
// @include       https://www.youtube.com/watch?v=0EY98EsPXs8
// @include       https://www.youtube.com/watch?v=F4qicK39ISc
// @include       https://www.youtube.com/watch?v=Y_0Ef3ftoek
// @include       https://www.youtube.com/watch?v=QarMI74GiAg
// @include       https://www.youtube.com/watch?v=0lQqK-ofK3M
// @include       https://www.youtube.com/watch?v=2xx_2XNxxfA
// @include       https://www.youtube.com/watch?v=MTW4sIL9Dpw
// @include       https://www.youtube.com/watch?v=M5V_IXMewl4
// @include       https://www.roblox.com/games/286090429/Arsenal
// @include       https://www.youtube.com/watch?v=jqCSRTSZUbs&ab_channel=%F0%9F%85%B1eans
// @include       https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
// @include       https://www.youtube.com/watch?v=WRDJMZsnSwg
// @include       https://www.youtube.com/watch?v=6DhRqIf-98I
// @include       https://www.youtube.com/watch?v=nz7-J0RN2CM&ab_channel=%E6%A5%B5%E7%9A%93
// @include       https://www.youtube.com/watch?v=htmN2kAwdkw&ab_channel=%E5%BB%A2%E7%89%87%E7%B3%BB
// @include       https://www.youtube.com/watch?v=o-YBDTqX_ZU
// @include       https://www.youtube.com/watch?v=GaAUS0GsG_M
// @include       http://www.lasesp.com/article/16325727300315435/Memes
// @include       https://www.youtube.com/watch?v=UMU1Qoa0wys
// @include       https://www.youtube.com/watch?v=VKrfRQOTdb8
// @include       https://gamejolt.com/p/damn-bppcuydv#comment-11602356
// @include       https://www.tomorrowtides.com/
// @include       https://www.tomorrowtides.com/reaer.html
// @include       https://www.thisworldthesedays.com/weg4.html
// @include       https://www.youtube.com/watch?v=dACK3j4uNjQ
// @include       https://www.youtube.com/watch?v=ZK1pNGmNBEc&list=PLN1LPImPw_PlDRy10sDskVGszKZcbXaDn
// @include       https://www.youtube.com/watch?v=j5a0jTc9S10&list=PL3KnTfyhrIlcudeMemKd6rZFGDWyK23vx&index=10
// @include       https://www.pinterest.com/pin/602356518904373196/
// @include       https://www.roblox.com/home
// @include       https://www.imperva.com/learn/application-security/google-hacking/
// @include       https://social.technet.microsoft.com/Forums/en-US/d4f8aa7f-c132-4579-9c97-63c705afd26c/how-can-i-disable-and-totally-remove-windows-10-family-safety?forum=win10itprosecurity
// @include       https://www.youtube.com/watch?v=UTHLKHL_whs
// @include       https://www.youtube.com/watch?app=desktop&v=xaazUgEKuVA
// @include       https://tenor.com/view/challenge-find-out-when-this-gif-ends-rickroll-rickrolled-hidden-rickroll-gif-22493495
// @include       https://downloadmoreram.com/
// @include       https://www.youtube.com/watch?v=072tU1tamd0&ab_channel=Majima
// @include       https://www.youtube.com/watch?v=dMCmWo7F3LU
// @include       https://www.sanfransentinel.com/immanuel-sucks.html
// @include       https://www.youtube.com/watch?v=PfDjnLPy6Uw
// @include       https://vimeo.com/148751763
// @include       https://kahoot.it/
// @include       https://discord.com/channels/@me/870794905528717362
// @include       https://www.latlmes.com/entertainment/parents-say-doja-cat-to-change-name-as-its-inappropriate-1
// @include       https://schoolbox.ofg.nsw.edu.au/
// @include       https://www.youtube.com/watch?v=rEcYUoEFS8A
// @include       https://www.latlmes.com/
// @include       https://www.youtube.com/watch?v=D_1U-vJzGo4
// @include       https://www.youtube.com/watch?v=zOd-e1au09Y
// @include       https://www.youtube.com/watch?v=dUpUJdhKglo
// @include       https://www.youtube.com/watch?v=lYBUbBu4W08
// @include       https://www.youtube.com/watch?v=chf71h2RSxc
// @include       https://c.tenor.com/AaJj7EJzzdAAAAAd/challenge-find-out-when-this-gif-ends.gif
// @include       https://studio.code.org/s/express-2020/lessons/9/levels/2
// @include       https://www.youtube.com/watch?v=lYBUbBu4W08&ab_channel=RickAstley-Topic
// @include       https://lh3.googleusercontent.com/fife/AAWUweWpuiRI40xCpO8p-Orodn2eq2vNeuPNYF13f1WkT6ZbajA8LhzKtj0q_yvIQbYpQr55sZIuiIXk9hhK1_OBr8UwyiDbFJLNqaoMd430CTpoGOVVyYGb7jrv5OsOTRpDHHiLaQWxY9U9iVt08Fg2g3EKXgusXkI5mNKcoEb_aSAjZY2gyUzMFGkugeSLi9rRU6PeRX1V1orcqBc0wlJpxvtyLu6tH6IhpBy5h91j1XnyHqI3Ru-FmiecW8oNE0VskI_CSt35pTLzjaPJz86BPDVPtmCW6yPcuphjscnQC0bqwM-KQvQH5Vye1abb3C6Dq5X6m4uZYv05K-fQTctUxFfetEGTrxbsVA0OmLqvDFpyNv8zeD-tX49j5m63ZqM4zigfonSTTFx7V2LOkwY2p2ErYIZPmoWstBolCI8BhTHVru1LtEJSeWeeQlJEMW41rP4WlAf3chkr89ktS4frCHQ5z2VgsxLmVS98gY7RYfA0pcA9k2DRm8Hi7zfmNeViocoWpGIfsKbMkkEZqs92aCHVXkaQmLsTU8ZT-6L6XhT7h4fIhgSAW3yNyLLfPM8KREwqVAnzAtuo4cjH81qDaxptylTCVSWFnuZOc_y-3Rg0D13NWiDZ_jwiD_dnhYuME7qXKn66aNefDJWr64n7QiOfITO0CXWq2f1mav_r_Rhtt-dJf-cdfa-9IJWiQk2wdhK4z-EbuGGb6LyixV-tpxu-A3GlIj4=w267-h200
// @include       https://lh3.googleusercontent.com/fife/AAWUweWhckypcKr10P7AY7PpvZQbpoKkpPmqd4i6h8kOzvVkJflMePtVx6NIMrZwpQDySU74NtW9vX17R6BUulrU2P3Tdpz59026cE3u3EijrSxa82aB_JnLEv0IV_fGs291sljl7YCMcFJeTIBGxkOHrN8qCP86RxYoWknHaD5qovDwIg2R5Q1gOrlHhrFNBWACg0g4JtWdrQJX_Z_AuAdmMgPH-jX1dcoe-yn_EL60NhhzwquD8ju-o4ReLOeDL5sU9Z5l1CeMTVg-wxLSIfm76fEFxnVARKruu5FrCKwr3op6VDuhIEw1W021xpwSMasvaBSl1wkuOIzfq0wsdZRTXMS5sjQls0zG7xOlmVDzA-U73si5WjSUFsJsAY0DPoOGQutHchQuZxLh5lL1jj3KAlPPgy7b3nOvW5LRB58yvMp9xf9xrBarRW_6nx7shMDVEn9cCFvC4h_EVSnkU6nzFhhEVR3ucnOz2w5vJnExIdkyDvY_lCNfhNOkGgWHxrfWEZl0A1pYEjcYK-kXaRvcIttWpJ5E2zKHSgEUYnjxxXAWOY166vjGlYtj3ZAwulR_OJWZ8uux2YjXZJ7_UiMWoyNw4apw-zPg9jWCTdIwVGRFz09Wuh0RZHKFQieA8DfObdtCBRvyMN2T7Xu_8JzW81nfLU_CuDp9r-7PEgD9RLQNGwUoHP4S4LHbFRBEupmx5miCbUMZWYepxP9lI8W0qRebV4JygsE=w267-h200
// @include       https://www.tomorrowtides.com/certamandt-2.html
// @include       https://mobile.twitter.com/IllinoisJCL/status/1377644339745189888
// @include       https://twitter.com/IllinoisJCL/status/1377644339745189888
// @include       https://rr.noordstar.me/
// @include       https://www.tomorrowtides.com/how-to-not-get-rickroled.html
// @include       https://www.youtube.com/watch?v=SEnNKehlonk
// @include       https://imagecolorpicker.com/
// @include       https://www.google.de/
// @include       https://www.google.de/search?q=rickroll&source=hp&ei=xeF3YeOnFse7tQaStoTQCg&iflsig=ALs-wAMAAAAAYXfv1V97wm6HDZGxQwKa4reVwYDPfnr0&ved=0ahUKEwijnveF-OfzAhXHXc0KHRIbAaoQ4dUDCAc&uact=5&oq=rickroll&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgsILhCABBDHARCjAjoLCC4QgAQQxwEQ0QM6BQguEIAEOgsILhCABBDHARCvAToHCAAQgAQQCjoHCC4QChCTAjoECC4QCjoKCC4QxwEQrwEQCjoECAAQCjoNCC4QxwEQrwEQChCTAjoICC4QgAQQkwI6DgguEIAEEMcBEK8BEJMCULoJWPsbYMsdaARwAHgAgAF8iAHHCZIBAzYuNpgBAKABAQ&sclient=gws-wiz
// @include       https://www.tomorrowtides.com/the-uno-reverse-war1.html
// @include       https://www.tomorrowtides.com/how-to-not-get-rickroll1
// @include       https://quran.com/
// @include       https://web.roblox.com/home
// @include       https://www.youtube.com/watch?v=u74qgdJmnaw&t=1s&ab_channel=Pheo9ixPlayz
// @include       https://www.youtube.com/watch?v=QDia3e12czc
// @include       https://www.youtube.com/results?search_query=rick+roll
// @include       https://www.youtube.com/watch?v=rTgj1HxmUbg
// @include       https://www.youtube.com/watch?app=desktop&v=kM9waTmnshI
// @include       https://qrco.de/bcW05n
// @include       https://www.youtube.com/watch?v=s7LS5lh0dLQ
// @include       https://studio.code.org/s/coursef-2019/lessons/7/levels/2
// @include       https://studio.code.org/s/coursef-2019/lessons/7/levels/4
// @include       https://www.youtube.com/watch?v=j5a0jTc9S10&list=PLFuNbp0NQ1D9ZMiyspdMS2hLtliqk9hVn&ab_channel=YourUncleMoe
// @include       https://www.theraleighregister.com/university-norte-dame-prep.html
// @include       https://www.youtube.com/watch?v=BT9h5ifR1tY
// @include       https://web.seesaw.me/
// @include       https://www.sanfransentinel.com/inside-the-human-mind.html
// @include       https://www.youtube.com/watch?v=h2XNMFvcRpc
// @include       https://learning.exemplar-education.com/lessonsystem/lesson-NO_HEAD_TABS.jsp?f=eNpdU1Fv2jAQ%2Fit%2B8tMGCRRWKkUTBdohAZsa2PqGTHIUq44dnS%2Bw%2FPudHdqqixTlfHe577vvzivw3tmZs4TOGMDvhasqZcucMFs5Va5iXBacAJa2bQ2Zia412Ebqkp36qAERjlmSpAk%2FaXojjbdbTQayJ6hBEZTCNwdCVZB2VhxaUTWGdM2lhDuK9MtAMKYYioumkyj1WXuHXgQkQSdlxSDpQgiV0rYE9BEi0LkN1syVkK1X6e%2Fxn2QiydW66PDXHY4uVEQOKLE8H2TXyHNlMm09KW6%2FrF9f%2Bm9l9l2897cykt8d6s95y6DZ%2Fi07pqm6XpbZIHw3qmJ0RSdmTLrwwRf5PuTBG8%2Fv9lnD5VOwQM%2BFbifjNJgxxDNo0EOs%2B0shiUFvLLpshCBJFTSYNuQioGSmSNq%2B1E5bytIkHQ9l4wG57nCUDEc3MnQThVs8L%2BY7aVQnI9j9dCf9Gbe6grU2RvuMfx4PJ6PB%2BNvtYPL%2Fj56asAeRGatUitnJXcpTg608avQfAYa4nj4yIiX75HhW%2BXY3X2y2sjD%2BEYOQiSwaxCjEIJV%2BhyY7EdX%2Brt83oNBydz34C1VtFH6FsumG3OMVfo%2F71hNUfVkomxfYHB4QwLQZYQNhAqYNTa50pSk7KuMhqMxzbWN7j%2FeRXie%2FKgreh2ivluvldjGfPeWrfCPVWbHU4cJ0uvZq%2B3Id1ozp626Od7GHUC4KQD5Nk%2FHktlaerdgnS5iDgXhFrpcsKp1Ty%2BJsfu5%2FLKbz%2FXZ6n4eNz0lR47MDuouHMnjWCl99lvQSGa7ZGWZMoYC3NTog7%2F6Sy12HdqLKjPKmrh3ydkjtp8a4S%2F6q6%2BX0KgWBp3XQIR7%2FAUP5fZs%3D#!
// @include       https://app.seesaw.me/#/item/item.69851fef-8835-43c1-bf5b-76664d38768a/duplicate/class/class.2e23edb9-8e91-406c-a348-8dc0fbc68b1c/user/person.cab36a15-b8cf-42fe-bea0-
// @include       https://app.seesaw.me/#/item/item.69851fef-8835-43c1-bf5b-76664d38768a/duplicate/class/class.2e23edb9-8e91-406c-a348-8dc0fbc68b1c/user/person.cab36a15-b8cf-42fe-bea0-
// @include       youtube.com/watch?v=uxIsiTo4VJo
// @include       youtube.com/watch?v=PIMrL4qXtJ0
// @include       youtube.com/watch?v=f2b1D5w82yU
// @include       youtube.com/watch?v=_0719DxMOUY
// @include       youtube.com/watch?v=xm_EMOdpDhc
// @include       internetisseriousbusiness.com#body
// @include       internetisseriousbusiness.com$script
// @include       youtube.com/watch?v=oHg5SJYRHA0
// @include       youtube.com/watch?v=lfO4Z5WEUuE
// @include       youtube.com/watch?v=atiNprQmjks
// @include       youtube.com/watch?v=ub_VBGajh-s
// @include       youtube.com/watch?v=FGEUClII8x0
// @include       youtube.com/watch?v=J3VnZMoh7sk
// @include       youtube.com/watch?v=LqXTU8YAGzo
// @include       youtube.com/watch?v=dS9DO6kx-Ek
// @include       youtube.com/watch?v=CZoJt0Sbqrs
// @include       youtube.com/watch?v=uYMIMPVK1vU
// @include       youtube.com/watch?v=IHKAgwIxUAY
// @include       youtube.com/watch?v=rfp7FbsnsbU
// @include       tinyurl.com/2nmscj#body
// @include       tinyurl.com/2nmscj$script
// @include       thekickback.com/rickroll/rickroll.php#body
// @include       thekickback.com/rickroll/rickroll.php$script
// @include       youtube.com/watch?v=ZOU8GIRUd_g
// @include       youtube.com/watch?v=b1WWpKEPdT4
// @include       youtube.com/watch?v=G_vas-7a7is
// @include       tobi-x.com/kate_moss_nude#body
// @include       tobi-x.com/kate_moss_nude$script
// @include       classpc.nl#body
// @include       classpc.nl$script
// @include       yougotrickrolled.com#body
// @include       yougotrickrolled.com$script
// @include       members.tele2.nl/class-pc#body
// @include       members.tele2.nl/class-pc$script
// @include       vids.myspace.com/index.cfm?fuseaction=vids.individual&videoid=25992858#body
// @include       vids.myspace.com/index.cfm?fuseaction=vids.individual&videoid=25992858$script
// @include       youtube.com/watch?v=RSsJ19sy3JI
// @include       youtube.com/watch?v=8aJjMOy-Ops
// @include       tinyurl.com/2tcnbl#body
// @include       tinyurl.com/2tcnbl$script
// @include       tinyurl.com/37ws8e#body
// @include       tinyurl.com/37ws8e$script
// @include       youtube.com/watch?v=-umtVthRGJI
// @include       palmsout.net/music/remixsunday/104/Never%20Gonna%20Give%20You%20Up%20%28Solly%20Remix%29.mp3#body
// @include       palmsout.net/music/remixsunday/104/Never%20Gonna%20Give%20You%20Up%20%28Solly%20Remix%29.mp3$script
// @include       youtube.com/watch?v=cjeogv9VUAE
// @include       youtube.com/watch?v=fmxGLQd3J0U
// @include       video.yahoo.com/watch/804885/3375801#body
// @include       video.yahoo.com/watch/804885/3375801$script
// @include       video.yahoo.com/watch/1313289/4562193#body
// @include       video.yahoo.com/watch/1313289/4562193$script
// @include       video.yahoo.com/watch/2013707/v2138974#body
// @include       video.yahoo.com/watch/2013707/v2138974$script
// @include       youtube.com/watch?v=gdpijMRhoT8
// @include       youtube.com/watch?v=1V_aE_Xdde8
// @include       youtube.com/watch?v=3HrSN7176XI
// @include       t1ny.us/7wp5i#body
// @include       t1ny.us/7wp5i$script
// @include       youtube.com/watch?v=MoUPdJrjkCM
// @include       bd.vg#body
// @include       bd.vg$script
// @include       youtube.com/watch?v=5uZr3JWYdy8
// @include       rubyurl.com/1H1G#body
// @include       rubyurl.com/1H1G$script
// @include       freeppcsecrets.com#body
// @include       freeppcsecrets.com$script
// @include       youtube.com/watch?v=uwnuL5Fy5g8
// @include       choose.yudia.net#body
// @include       choose.yudia.net$script
// @include       keiraknightley.ytmnd.com#body
// @include       keiraknightley.ytmnd.com$script
// @include       warlocksnerfed.ytmnd.com#body
// @include       warlocksnerfed.ytmnd.com$script
// @include       rurl.org/2vq#body
// @include       rurl.org/2vq$script
// @include       smouch.net/lol#body
// @include       smouch.net/lol$script
// @include       youtube.com/watch?v=r8tXjJL3xcM
// @include       youtube.com/watch?v=3KANI2dpXLw
// @include       youtube.com/watch?v=Yu_moia-oVI
// @include       ravenstorm.byethost15.com#body
// @include       ravenstorm.byethost15.com$script
// @include       raygoldmodels.com#body
// @include       raygoldmodels.com$script
// @include       rr.rezbit.com#body
// @include       rr.rezbit.com$script
// @include       youtube.com/watch?v=VVjUWKSZSsc
// @include       youtube.com/watch?v=lfao5IToml4
// @include       youtube.com/watch?v=eLiXPfl8EPY
// @include       youtube.com/watch?v=lzSjyzqfegI
// @include       youtube.com/watch?v=AP12uZvfvag
// @include       reichroll.com#body
// @include       reichroll.com$script
// @include       bringvictory.com#body
// @include       bringvictory.com$script
// @include       youtube.com/watch?v=XfTUDW93z6E
// @include       collegehumor.com/video:1809841#body
// @include       collegehumor.com/video:1809841$script
// @include       evanball.com#body
// @include       evanball.com$script
// @include       sirpnut.info/sorry.jpg#body
// @include       sirpnut.info/sorry.jpg$script
// @include       ecritters.biz/sr#body
// @include       ecritters.biz/sr$script
// @include       youtube.com/watch?v=6SYVdI7Llrg
// @include       youtube.com/watch?v=vf79MCuQ8jM
// @include       techsmartly.net#body
// @include       techsmartly.net$script
// @include       youtube.com/watch?v=QumbExFAj-U
// @include       epicwinrar.com#body
// @include       epicwinrar.com$script
// @include       203.24.182.170#body
// @include       203.24.182.170$script
// @include       youtube.com/watch?v=xAp3HqpE7V8
// @include       youtube.com/watch?v=YWn54TjfBkk
// @include       youtube.com/watch?v=I6_0tpqg3ZE
// @include       youtube.com/watch?v=IpjGmx2v6bM
// @include       comicwonder.com/joke/8a46a9b4a#body
// @include       comicwonder.com/joke/8a46a9b4a$script
// @include       tinyurl.com/ynupj4#body
// @include       tinyurl.com/ynupj4$script
// @include       ali3ns.net#body
// @include       ali3ns.net$script
// @include       prankdialer.com/rickroll.php#body
// @include       prankdialer.com/rickroll.php$script
// @include       todo.is#body
// @include       todo.is$script
// @include       niya.cc/flash/rick#body
// @include       niya.cc/flash/rick$script
// @include       paulsmom.prohosts.org#body
// @include       paulsmom.prohosts.org$script
// @include       youtube.com/watch?v=yxnWl63Avo4
// @include       youtube.com/watch?v=hq05IRf0dBQ
// @include       stucknut.com/locker/files/jessica.gif#body
// @include       stucknut.com/locker/files/jessica.gif$script
// @include       youtube.com/watch?v=gLVtavM962w
// @include       youtube.com/watch?v=RzoZGNsJ71w
// @include       almightypickle.deviantart.com/art/a-very-stupid-flash-movie-83440015#body
// @include       almightypickle.deviantart.com/art/a-very-stupid-flash-movie-83440015$script
// @include       youtube.com/watch?v=veFrQTKQy7A
// @include       punahou.com#body
// @include       punahou.com$script
// @include       youtube.com/watch?v=NZ-AAD7Ci_c
// @include       youtube.com/watch?v=tazYxtJcwCc
// @include       ebaumsworld.com/video/watch/411687#body
// @include       ebaumsworld.com/video/watch/411687$script
// @include       fuckdreamhost.com#body
// @include       fuckdreamhost.com$script
// @include       youtube.com/watch?v=cxwxBheZniM
// @include       youtube.com/watch?v=gvUiLtwlEl8
// @include       youtube.com/watch?v=DpPhnECPe2I
// @include       youtube.com/watch?v=HiaBjpzLgQI
// @include       rick-rolld.com#body
// @include       rick-rolld.com$script
// @include       youtube.com/watch?v=z-HWXfRKkJU
// @include       youtube.com/watch?v=MJCH_wT9TaU
// @include       apoke.com#body
// @include       apoke.com$script
// @include       tinyurl.com/5sb29l#body
// @include       tinyurl.com/5sb29l$script
// @include       youtube.com/watch?v=5F5nc1bAaKw
// @include       zeroboard.com/16979949#0#body
// @include       zeroboard.com/16979949#0$script
// @include       youtube.com/watch?v=EEbzptEFsKk
// @include       youtube.com/watch?v=zGm0nGF_y2E
// @include       youtube.com/watch?v=AS35zlAdaSQ
// @include       rickroll.net#body
// @include       rickroll.net$script
// @include       ww.rickroll.net#body
// @include       ww.rickroll.net$script
// @include       todaysbigthing.com/2008/04/07#body
// @include       todaysbigthing.com/2008/04/07$script
// @include       youtube.com/watch?v=LeSnAn-Sc0g
// @include       rickrolling.com/lol#body
// @include       rickrolling.com/lol$script
// @include       tinyurl.com/4xur8r#body
// @include       tinyurl.com/4xur8r$script
// @include       url.uppix.net/NFWGJ#body
// @include       url.uppix.net/NFWGJ$script
// @include       tinyurl.com/rickrolll#body
// @include       tinyurl.com/rickrolll$script
// @include       mxweas.com/docs/jailbreakservhack#body
// @include       mxweas.com/docs/jailbreakservhack$script
// @include       youtube.com/watch?v=z2kThcO6ig8
// @include       youtube.com/watch?v=xpupxRzumYs
// @include       asongbyagayguy.ytmnd.com#body
// @include       asongbyagayguy.ytmnd.com$script
// @include       youtube.com/watch?v=f8FHqEIzSlE
// @include       tinyurl.com/britneyspearsXXX#body
// @include       tinyurl.com/britneyspearsXXX$script
// @include       youtube.com/watch?v=8Set3JpJJ4w
// @include       youtube.com/watch?v=v7cyQ-dVaAM
// @include       1227.com#body
// @include       1227.com$script
// @include       youtube.com/watch?v=eKDcl0V6o6k
// @include       youtube.com/watch?v=hyX_krrTBZ0
// @include       youtube.com/watch?v=q6NwqFlctZY
// @include       youtube.com/watch?v=fMzkMpMraFY
// @include       youtube.com/watch?v=iJbwc4wm5Y0
// @include       youtube.com/watch?v=VBY4TV5qK-4
// @include       video.hexxeh.net#body
// @include       video.hexxeh.net$script
// @include       technocolbert.co.nr#body
// @include       technocolbert.co.nr$script
// @include       youtube.com/watch?v=Zc2tpMgz6MI
// @include       rasher.dk/r/linode-dns#body
// @include       rasher.dk/r/linode-dns$script
// @include       rasher.dk/r#body
// @include       rasher.dk/r$script
// @include       youtube.com/watch?v=ywoqy9PBN-0
// @include       liner.org#body
// @include       liner.org$script
// @include       youtube.com/watch?v=lAQIiNTH46I
// @include       tinyurl.com/KIM-KARDASHIAN-SEX-TAPE#body
// @include       tinyurl.com/KIM-KARDASHIAN-SEX-TAPE$script
// @include       youtube.com/watch?v=PXrHCBoEj7g
// @include       pottermisleading.ytmnd.com#body
// @include       pottermisleading.ytmnd.com$script
// @include       youtube.com/watch?v=piLTpv1eKdU
// @include       youtube.com/watch?v=b43GgNbz9fg
// @include       youtube.com/watch?v=67KOFEEOhkI
// @include       youtube.com/watch?v=ZIQZHqNQODo
// @include       youtube.com/watch?v=aSzhxllE0RM
// @include       johncow.com/moo.html#body
// @include       johncow.com/moo.html$script
// @include       youtube.com/watch?v=lp6nr-rD_g8
// @include       sprigler.com/steven#body
// @include       sprigler.com/steven$script
// @include       youtube.com/watch?v=vp8fkB0uwd0
// @include       tinyurl.com/CELEBRITY-XXX-VIDS#body
// @include       tinyurl.com/CELEBRITY-XXX-VIDS$script
// @include       youtube.com/watch?v=y5Ja-E529sU
// @include       youtube.com/watch?v=Xsvi9uNrDSI
// @include       youtube.com/watch?v=RgIDuaxiT0w
// @include       youtube.com/watch?v=yXGqsnkLg0A
// @include       just-different.info/secret#body
// @include       just-different.info/secret$script
// @include       crappypc.com#body
// @include       crappypc.com$script
// @include       tinyurl.com/yowxeq#body
// @include       tinyurl.com/yowxeq$script
// @include       youtube.com/watch?v=ABUhOJxZQmg
// @include       youtube.com/watch?v=4ynGOr9vmyc
// @include       youtube.com/watch?v=UDTGvgE5eJw
// @include       reichrolled.com#body
// @include       reichrolled.com$script
// @include       rr.rezbit.com/blog/021107/rick-astley-speaks-about-rickroll.html#body
// @include       rr.rezbit.com/blog/021107/rick-astley-speaks-about-rickroll.html$script
// @include       zideo.nl/index.php?option=com_podfeed&zideo=6c4971596d513d3d&playzideo=6c344f596d31593d&Itemid=#body
// @include       zideo.nl/index.php?option=com_podfeed&zideo=6c4971596d513d3d&playzideo=6c344f596d31593d&Itemid=$script
// @include       i65games.tk#body
// @include       i65games.tk$script
// @include       8chan.henriwatson.com/b#body
// @include       8chan.henriwatson.com/b$script
// @include       youtube.com/watch?v=X-j828DqqnY
// @include       youtube.com/watch?v=65I0HNvTDH4
// @include       youtube.com/watch?v=thNTPin2RBY
// @include       noelurl.easyasweb.eu/u0Rx744fi#body
// @include       noelurl.easyasweb.eu/u0Rx744fi$script
// @include       krazykustoms.co.cc/phpBB3/index.php#body
// @include       krazykustoms.co.cc/phpBB3/index.php$script
// @include       youtube.com/watch?v=R5P1_U7LZX8
// @include       adurah.com/img/hp7_spoilers.jpg#body
// @include       adurah.com/img/hp7_spoilers.jpg$script
// @include       tinyurl.com/5a3jqf#body
// @include       tinyurl.com/5a3jqf$script
// @include       bit.ly/1628nB#body
// @include       bit.ly/1628nB$script
// @include       youtube.com/watch?v=4TJB9FQo45E
// @include       youtube.com/watch?v=A1sgzEDUG-o
// @include       youtube.com/watch?v=5kQKh2tdisQ
// @include       you-host.info#body
// @include       you-host.info$script
// @include       youtube.com/watch?v=_FyXC-SsAPE
// @include       74.125.95.104/search?q=cache:YLZLcPVmjrsJ:smouch.net/lol/+rick+roll&hl=en&ct=clnk&cd=5&gl=us#body
// @include       74.125.95.104/search?q=cache:YLZLcPVmjrsJ:smouch.net/lol/+rick+roll&hl=en&ct=clnk&cd=5&gl=us$script
// @include       rickrolled.fr#body
// @include       rickrolled.fr$script
// @include       pspemporium.webs.com/rickdance.html#body
// @include       pspemporium.webs.com/rickdance.html$script
// @include       krazykustoms.co.cc/pages#body
// @include       krazykustoms.co.cc/pages$script
// @include       finalclan.net#body
// @include       finalclan.net$script
// @include       newroupdates.tk#body
// @include       newroupdates.tk$script
// @include       irc.infinitynet.info#body
// @include       irc.infinitynet.info$script
// @include       youtube.com/watch?v=IVvl_R2jYMo
// @include       youtube.com/watch?v=SGi7qi_y0Jw
// @include       youtube.com/watch?v=-HRRGn6tNd4
// @include       furryartpile.com#body
// @include       furryartpile.com$script
// @include       tinyurl.com/244u3n#body
// @include       tinyurl.com/244u3n$script
// @include       youtube.com/watch?v=WpEVccrkYQ0
// @include       tinyurl.com/2w4apm#body
// @include       tinyurl.com/2w4apm$script
// @include       moourl.com/09773#body
// @include       moourl.com/09773$script
// @include       youtube.com/watch?v=Kmt4wrn1MTk
// @include       youtube.com/watch?v=vvs7cXmVwN8
// @include       youtu.be/2ZPoD0zHXXM
// @include       youtu.be/5bngibix5PI
// @include       youtu.be/9DImRZERJNs
// @include       youtube.com/watch?v=5bngibix5PI
// @include       youtube.com/watch?v=9DImRZERJNs
// @include       https://www.youtube.com/watch?v=2ZPoD0zHXXM
// @include       https://www.youtube.com/watch?v=M8LzQi0WN_s
// @include       https://www.youtube.com/watch?v=geggkvKRW5E
// @include       youtu.be/M8LzQi0WN_s
// @include       youtu.be/geggkvKRW5E
// @include       https://www.youtube.com/watch?v=kB7EH3dLGM4
// @include       youtu.be/kB7EH3dLGM4
// @include       youdontknowwhoiam.org
// @include       youtube.com/watch?v=v_y2GC4IE58
// @include       youtu.be/v_y2GC4IE58
// @include       https://www.youtube.com/c/RickastleyCoUkOfficial
// @exclude     *youtube.com/
// @grant       none
// ==/UserScript==

window.location.href="https://moongazer07.github.io/docs/index.html";
